version: '3'
services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: unless-stopped
    ports:
      - "5230:5230"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/memos:/var/opt/memos
    networks:
      memos_net:

networks:
  memos_net: